/* HERO Store data — auto-generated */
window.HERO_DATA = {
  "version": 1,
  "updatedAt": "2026-10-10T09:16:59.538Z",
  "categories": [
    {
      "id": "games",
      "name": "الألعاب",
      "icon": "🎮"
    },
    {
      "id": "tools",
      "name": "الأدوات",
      "icon": "🛠️"
    },
    {
      "id": "education",
      "name": "التعليم",
      "icon": "📚"
    },
    {
      "id": "design",
      "name": "التصميم",
      "icon": "🎨"
    },
    {
      "id": "digital-products",
      "name": "منتجات رقمية",
      "icon": "📦"
    },
    {
      "id": "services",
      "name": "الخدمات",
      "icon": "💼"
    }
  ],
  "products": [
    {
      "id": "ts003",
      "name": "استديو الترند",
      "seller": "HERO",
      "category": "tools",
      "description": "أداة تصنع الريلز في ثواني",
      "emoji": "📦",
      "image": "assets/images/123.png",
      "c1": "#6366f1",
      "c2": "#a855f7",
      "price": "0",
      "priceValue": 0,
      "rating": 4.5,
      "reviews": 27,
      "ctaText": "",
      "featured": true,
      "new": false,
      "tags": [
        "محتوى",
        "ريلز",
        "منشيء",
        "منشيء محتوى",
        "فيسبوك",
        "يوتيوب",
        "تيك توك",
        "انستا",
        "انستاجرام"
      ],
      "buyUrl": "https://studio.hero1.vip/",
      "landingUrl": "https://studio.hero1.vip/product-pitch-ar.html",
      "landingHtml": ""
    },
    {
      "id": "ts001",
      "name": "سوبر هيرو القدرات والتحصيلي",
      "seller": "HERO",
      "category": "education",
      "description": "طريقك للاستعداد للقدرات والتحصيلي بطريقة منظمة وسهلة تساعدك على التعلم والمراجعة والاستعداد للاختبار.",
      "emoji": "📦",
      "image": "/assets/001.png",
      "c1": "#6366f1",
      "c2": "#a855f7",
      "price": "0",
      "priceValue": 0,
      "rating": 4.5,
      "reviews": 7,
      "ctaText": "",
      "featured": true,
      "new": false,
      "tags": [
        "القدرات",
        "اختبار القدرات",
        "القدرات الكمي",
        "القدرات اللفظي",
        "تأسيس قدرات",
        "شرح القدرات",
        "تجميعات القدرات",
        "أسئلة قدرات مع الحل",
        "تدريب قدرات",
        "خطة مذاكرة التحصيلي",
        "الاستعداد للقبول الجامعي",
        "اختبارات القبول الجامعي في السعودية",
        "طلاب الثانوية السعودية",
        "Hero Academy",
        "أكاديمية هيرو",
        "اختبار قدرات تجريبي"
      ],
      "buyUrl": "https://saatgat.hero1.vip/",
      "landingUrl": "",
      "landingHtml": ""
    },
    {
      "id": "ts004",
      "name": "مقياس نبض التميز",
      "seller": "HERO",
      "category": "tools",
      "description": "اكتشف نقاط قوة طفلك \nتقييم نمائي شامل • أنشطة يومية مخصصة • متابعة تطور طفلك يوماً بيوم",
      "emoji": "📦",
      "image": "/assets/004.png",
      "c1": "#6366f1",
      "c2": "#a855f7",
      "price": "0",
      "priceValue": 0,
      "rating": 5,
      "reviews": 9,
      "ctaText": "",
      "featured": true,
      "new": false,
      "tags": [
        "تنمية مهارات الطفل",
        "تقييم قدرات الأطفال",
        "اكتشاف مواهب الأطفال",
        "نقاط قوة الطفل",
        "تطوير شخصية الطفل",
        "تقييم نمو الطفل",
        "تنمية قدرات الأطفال",
        "تربية الأطفال",
        "التربية الإيجابية",
        "فهم شخصية الطفل",
        "كيف أكتشف موهبة طفلي",
        "كيف أطور مهارات طفلي",
        "نقاط القوة والضعف عند الأطفال",
        "التعامل مع سلوك الأطفال",
        "تنمية ذكاء الطفل",
        "تحسين ثقة الطفل بنفسه",
        "دعم نمو الطفل"
      ],
      "buyUrl": "",
      "landingUrl": "https://nabdh.hero1.vip/nabd.html",
      "landingHtml": ""
    },
    {
      "id": "ts005",
      "name": "صفحة هبوط + اعلان مجاني لأول 100 معلن",
      "seller": "HERO",
      "category": "design",
      "description": "للحجز تواصل مع الدعم الفني على تيليجرام : https://t.me/heroapp1",
      "emoji": "📦",
      "image": "/assets/005.png",
      "c1": "#6366f1",
      "c2": "#a855f7",
      "price": "0",
      "priceValue": 0,
      "rating": 4.5,
      "reviews": 0,
      "ctaText": "",
      "featured": true,
      "new": false,
      "tags": [
        "HeroStore",
        "صفحة_هبوط",
        "تسويق_إلكتروني",
        "مشاريع_صغيرة",
        "رواد_الأعمال",
        "التجارة_الإلكترونية",
        "التسويق_الرقمي",
        "أصحاب_المشاريع",
        "صفحات_الهبوط"
      ],
      "buyUrl": "https://t.me/heroapp1",
      "landingUrl": "",
      "landingHtml": ""
    }
  ],
  "settings": {
    "storeName": "HERO",
    "storeTag": "STORE",
    "logoEmoji": "H",
    "logoImage": "assets/logo.png",
    "heroTitle": "لا تشتري ما يشتريه الجميع ! اكتشف منتجات وأدوات رقمية مميزة",
    "heroSub": "أدوات، ألعاب، دورات، تصاميم وخدمات رقمية — منتقاة يدويًا، جاهزة فورًا.",
    "heroBadge": "✨ جديد — منتجات مختارة بعناية",
    "heroCta": "اكتشف المنتجات",
    "heroCta2": "تصفّح التصنيفات",
    "heroImage": "",
    "primaryColor": "#6366F1",
    "secondaryColor": "#A855F7",
    "accentColor": "#EC4899",
    "featuredTitle": "منتجات مميزة",
    "latestTitle": "أحدث المنتجات",
    "catsTitle": "تصفّح التصنيفات",
    "articlesTitle": "📝 المقالات",
    "articlesSub": "نصائح، شروحات، وأفكار مفيدة",
    "showFeatured": true,
    "showLatest": true,
    "showCats": true,
    "showArticles": true,
    "footerAbout": "كتالوج منتجات رقمية: أدوات، ألعاب، دورات، تصاميم وخدمات.",
    "footerCopyright": "© 2026 HERO — جميع الحقوق محفوظة.",
    "social": {
      "twitter": "",
      "instagram": "",
      "youtube": "",
      "tiktok": "",
      "facebook": "",
      "whatsapp": "",
      "email": "",
      "website": ""
    },
    "metaTitle": "HERO Store — منتجات رقمية مميزة | أدوات، ألعاب، دورات",
    "metaDescription": "HERO Store — منتجات رقمية مميزة: أدوات، ألعاب، دورات، تصاميم وخدمات. جودة منتقاة، وصول فوري. اكتشف الفرق الآن.\n\n",
    "ogImage": ""
  },
  "analytics": {
    "GA4_ID": "G-EFXR4NFC0G",
    "GTM_ID": "GTM-PJB2HZC4",
    "ADS_ID": "",
    "ADS_CONVERSION_LABEL": ""
  }
};
